apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:  # Change "templates" to "template"
    metadata:
      labels:
        app: nginx
    spec:
      containers:  # Correct "conatainers" to "containers"
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80  # Correct "conatinerPort" to "containerPort"
